### ISSUE TITLE
thread 'main' panicked at src/version.rs:168:62

### ISSUE THREAD

**Issue by zvonkok** [cncf-tags/container-device-interface-rs#40]
WIth this CDI spec we trigger a panic

```
❯ cat /etc/cdi/test.json 
{
  "cdiVersion": "0.6.0",
  "kind": "vendor.com/device",
  "devices": [
    {
      "name": "myDevice",
      "annotations": {
        "whatever": "false",
        "whenever": "true"
      },
      "containerEdits": {
        "deviceNodes": [
          {
            "path": "/dev/rtc0"
          }
        ]
      }
    }
  ]
}
```

```
thread 'main' panicked at src/version.rs:168:62:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Apokleos** [comment]
sure, I will fix it today

**Comment by zvonkok** [comment]
This is fixed in the other PR I posted before
